### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by simonkrempin** [Johannes-01/Software_Engineering_I#1]
Als ein neuer Nutzer möchte ich mit einer Ausschlag geben Landing Page begrüßt werden, damit ich weiß wofür die Website gedacht ist und wohin es weiter geht

Akzeptanzkriterien

- [x] Umsetzung des Mocks
- [x] Ist man angemeldet und drückt auf den Button wird in man auf das Dashboard weitergeleitet
- [x] ist man nicht angemeldet und drückt auf den Button wird man auf die Login Seite auf /login weitergeleitetet

UI Mock
![image](https://github.com/user-attachments/assets/89dbf72a-9e85-416e-a526-c4fd521b4a9d)

**Comment by Johannes-01** [comment]
What font is this?
