### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by simonkrempin** [Johannes-01/Software_Engineering_I#2]
Als User möchte ich mich bei der Applikation anmelden können damit, damit ich Nutzer basierte Services wie Auswahlmappen speichern kann

Akzeptanzkriterien 
- [ ] Oberfläche wie im Mock
- [ ] Email und Passwort sind Pflichtfelder, wenn auf login geklickt wird und eines der Felder nicht gefüllt ist, soll eine Fehlernachricht unter dem Feld erstellen
- [ ] wenn auf Login gedrückt wird und beide Felder gefüllt sind soll eine Request gegen das Backend gemacht werden unter /api/login
- [ ] wenn der login funktioniert soll der auth token gespeichert werden und auf die Dashboard Seite /gallery gerouted werden
- [ ] wenn der login fehlschlägt wird der Fehler "E-Mail oder Passwort falsch" angezeigt
- [ ] wenn auf registrieren geklickt wird, sollte auf /register umgeleitet werden

Mock für das User Interface
![image](https://github.com/user-attachments/assets/026a2f56-d3ff-4115-b2e7-b7530cdad07a)

**Comment by Johannes-01** [comment]
Am User Objekt kann direkt eine der Rollen (Kunsthändler oder Kunde) hinterlegt werden. Wenn wir Langeweile haben können wir auch ein Benutzermanagement bauen.
