### ISSUE TITLE
Email verification was successful page

### ISSUE THREAD

**Issue by Johannes-01** [Johannes-01/Software_Engineering_I#33]
If the user has confirmed the email and the user is redirected to /auth/confirm/ show that the user has successfully verified his email adress.

Also add a button to get to the landing.

**Comment by simonkrempin** [comment]
Das sollte aus den Anforderungen gelöscht werden, weil wir kein vollumfängliches Nutzermanagement brauchen und eine Validierung von der E-Mail unnötiger overhead wäre. Wenn du keinen weiteren Einwand hast, dann würde ich das Ticket schließen.

**Comment by Johannes-01** [comment]
Kann man issues archivieren?
